- name: Create grafana database
  mysql_db:
    name: grafana
    state: present
    login_user: root
    login_password: "{{ password }}"

- name: Create grafana database user
  mysql_user:
    name: grafana
    password: "{{ password }}"
    priv: grafana.*:ALL,GRANT
    host: localhost
    login_user: root
    login_password: "{{ password }}"

- name: Edit /etc/grafana/grafana.ini
  ini_file:
    dest: /etc/grafana/grafana.ini
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { section: "server", option: "http_port", value: "{{ grafana_port }}" }
    - { section: "server", option: "root_url", value: "%(protocol)s://%(domain)s:%(http_port)s{{ grafana_prefix }}"}
    - { section: "database", option: "type", value: "mysql"}
    - { section: "database", option: "host", value: "localhost:3306"}
    - { section: "database", option: "name", value: "grafana"}
    - { section: "database", option: "user", value: "grafana"}
    - { section: "database", option: "password", value: "{{ password }}"}
    - { section: "analytics", option: "reporting_enabled", value: "false" }
    - { section: "auth.ldap", option: "enabled", value: "true" }
    - { section: "security", option: "admin_password", value: "{{ password }}" }

- name: Restart grafana
  service: name=grafana-server state=restarted enabled=yes
