- name: Check for password file
  stat: path=/root/.password
  register: password_file

- name: Get password from file
  command: cat /root/.password
  register: password_from_file
  when: password_file.stat.exists == True
  changed_when: False

- name: Create password
  command: /usr/bin/openssl rand -base64 10
  register: generated_password
  when: password_file.stat.exists == False

- name: Pick the right password
  set_fact:
    password: "{{ password_from_file.stdout if password_file.stat.exists == True else generated_password.stdout }}"

- name: Store password in file
  copy: content="{{ password }}\n" dest=/root/.password
  when: password_file.stat.exists == False
