- name: Install nginx
  yum: name=nginx

- name: Setup nginx
  template: src=router.conf.j2 dest=/etc/nginx/conf.d/router.conf

- name: Restart nginx
  service: name=nginx state=restarted enabled=yes
